### ISSUE TITLE
Question: Attention needed

### ISSUE THREAD

**Issue by LGithub763** [RogueEdit/pyRogue#193]
**A clear and concise description of what the question is.**
- Response 403 - Forbidden. We have no authorization to access the resource.
- I'm getting this message every time i try to log in, the only difference is that I am using a different wifi at another location, and I cannot use the program unless on the original wifi I downloaded it on
- how can i fix this issue?

**Comment by JulianStiebler** [comment]
Related to your network. Some residential IP's are somehow blocked, nothing we can do.
